config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'foods#index'

  devise_for :users, controllers: { registrations: 'users/registrations' }

  resources :foods
  get 'recipe_foods/new/:id', to: 'recipe_foods#new', as: 'new_recipe_food'
  resources :recipe_foods
  resources :recipes
  resources :general_shopping_lists, only: [:index]
  resources :public_recipes, only: [:index]
  # Define any additional custom routes if needed
  
end

app/controllers/public_recipes_controller.rb
class PublicRecipesController < ApplicationController
  def index
    @recipes = Recipe.includes(:user, :foods, :recipe_foods).where(public: true).order(created_at: :desc)
  end
end

app/views/public_recipes/_recipe_card.html.erb
<div class="bg-warning-subtle border border-black column-gap-3 d-flex justify-content-evenly my-3 p-3 rounded-3 align-items-center">
  <div class="fs-4">
    <%= link_to recipe.name, recipe_path(recipe.id) %>
    <br> By: <%= recipe.user.name %>
  </div>
  <div class="">  
      <% total_price = 0 %>
      <% food_count = recipe.foods.count %>
      <% recipe.recipe_foods.each do |recipe_food| %>
      <% total_price += recipe_food.quantity * recipe_food.food.price %>
      <% end %>
     <span>Total Food Items: <%= food_count %></span> <br>
    <span>Total Price: $<%= total_price %></span>
  </div>
</div>

app/views/public_recipes/index.html.erb
<%= render 'devise/shared/navbar' %>

<div class="container mt-5">
  <section class="p-3 text-center d-flex flex-column row-gap-3">
    <%if@recipes.empty?%>
      <div class="row">
        <div class="col">    
          <div class="alert alert-primary text-center" role="alert">
              There is no public recipe.
          </div>
        </div>
      </div>    
    <%else%>
      <div class="row">
        <div class="col">
          <h1 class="text-center">Public Recipes</h1>
           <%= render partial: 'recipe_card', collection: @recipes, as: :recipe %> 
        </div>
      </div>
    <%end%>
  </section>
</div>



  
  