config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'foods#index'

  devise_for :users, controllers: { registrations: 'users/registrations' }

  resources :foods
  get 'recipe_foods/new/:id', to: 'recipe_foods#new', as: 'new_recipe_food'
  resources :recipe_foods
  resources :recipes
  resources :general_shopping_lists, only: [:index]
  resources :public_recipes, only: [:index]
  # Define any additional custom routes if needed
  
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :user
  has_many :recipe_foods, dependent: :destroy
  has_many :foods, through: :recipe_foods, dependent: :destroy

  validates :name, presence: true
  validates :preparation_time, numericality: { greater_than: 0 }
  validates :cooking_time, numericality: { greater_than: 0 }
  validates :description, presence: true
  validates :user_id, presence: true
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :authenticate_user!

  def index
    @user = current_user
    @recipes = @user.recipes
  end

  def show
    @recipe = Recipe.find(params[:id])
  end

  def update
    @recipe = Recipe.find(params[:id])
    return unless @recipe.update(update_params)

    redirect_to recipe_path(@recipe)
  end

  def destroy
    @recipe = Recipe.find(params[:id])
    authorize! :destroy, @recipe

    return unless @recipe.destroy

    RecipeFood.where(recipe_id: @recipe).delete_all

    redirect_to recipes_path
  end

  def new
    @recipe = Recipe.new
  end

  def create
    @recipe = current_user.recipes.new(recipes_params)
    if @recipe.save
      redirect_to recipe_path(@recipe.id)
    else
      render :new
    end
  end

  private

  def recipes_params
    params.require(:recipe).permit(:name, :preparation_time, :cooking_time, :description, :public)
  end

  def update_params
    params.require(:recipe).permit(:public)
  end
end

app/helpers/recipes_helper.rb
module RecipesHelper
  def trim_text(text)
    text.length <= 85 ? text : "#{text[0..200]}..."
  end

  def delete_button(recipe)
    content = ''
    if can?(:destroy, recipe)
      content << button_to('Remove', recipe_path(recipe), method: :delete,
                                                          class: 'fs-5 border border-0 bg-transparent
                                                                  text-decoration-underline text-primary').to_s
    end
    content.html_safe
  end

  def public?(recipe)
    content = ''
    if can?(:update, recipe)
      content = if recipe.public
                  (button_to '', recipe_path(recipe), method: :patch, params: { recipe: { public: false } },
                                                      remote: true, class: 'public-btn').to_s
                else
                  (button_to '', recipe_path(recipe), method: :patch, params: { recipe: { public: true } },
                                                      remote: true, class: 'public-btn-false').to_s
                end
    end
    content.html_safe
  end

  def details_buttons(recipe)
    content = ''
    if can?(:create, recipe)
      content << (link_to 'Generate shopping list', general_shopping_lists_url,
                          class: 'buttons btn btn-primary auto-width').to_s
      content << (link_to 'Add ingredient', new_recipe_food_path(recipe),
                          class: 'buttons btn btn-primary auto-width').to_s
    end
    content.html_safe
  end

  def recipe_actions(food, recipe_food)
    content = ''
    unless can?(:update, food) && can?(:destroy, food)
      content << '<span>No actions permited</span>'
      return content.html_safe
    end
    content << (link_to 'Modify', edit_recipe_food_path(recipe_food), class: 'link-info p-2').to_s
    content << (button_to 'Remove', recipe_food_path(food), method: :delete, class: 'btn btn-link link-warning').to_s
    content.html_safe
  end

  def foods(current_recipe)
    recipe_foods_list = current_recipe.recipe_foods
    foods = []
    recipe_foods_list.each { |recipe_food| foods << Food.where(id: recipe_food.food_id) }

    new_foods = []
    foods.each do |food|
      recipe = recipe_foods_list.filter { |elem| elem.food_id == food[0].id }
      item = { food: food[0], recipe: recipe[0] }
      new_foods << item
    end
    new_foods
  end
end

app/views/recipes/_recipe_card.html.erb
<div class="border border-black d-flex p-3 rounded-3 m-3">
  <div class="align-items-center col-6 d-flex flex-column fs-3">
    <%= link_to recipe.name, recipe_path(recipe.id) %>
    <%= delete_button(recipe) %>
  </div>
  <div class="fs-5 align-items-center"><%= trim_text(recipe.description) %></div>
</div>      

app/views/recipes/_table_rows.html.erb
<tr>
  <td><%= foods[:food].name %></td>
  <td><%= foods[:recipe].quantity %></td>
  <td><%= foods[:food].price * foods[:recipe].quantity %></td>
  <td class="d-flex"><%= recipe_actions(foods[:food], foods[:recipe]) %></td>
</tr>

app/views/recipes/index.html.erb
<%= render 'devise/shared/navbar' %>
<section class="p-3 text-center d-flex flex-column row-gap-3">
<div class="container mt-5">
  <div class="row">
    <div class="col">
      <h2><%= @user.name %>'s Recipes</h2>
      <span class="d-flex justify-content-end m-3"><%= link_to 'Create new recipe', new_recipe_path, class: 'btn btn-primary' %></span>
    </div>
    <div>
      <%= render partial: 'recipe_card', collection: @recipes, as: :recipe %>
    </div>
  </div>
</div>
</section>

app/views/recipes/new.html.erb
<%= render partial: 'devise/shared/navbar' %>

<section class="container mt-5">
  <h2 class="p-3 text-center">Create new recipe</h2>
  <% if @recipe.errors.any? %>
      <div class="container alert alert-danger w-50" role="alert" id="error_explanation">
        <ul class="m-0">
          <% @recipe.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <%= form_with(model: @recipe, class: 'mt-3') do |form| %>
      <div class="container d-flex flex-column align-items-center">
        <div class="mb-3 w-50">
          <%= form.label :name, "Recipe's name:", class: 'form-label' %>
          <%= form.text_field :name, :required => true, class: 'form-control' %>
        </div>

        <div class="mb-3 w-50">
          <%= form.label :preparation_time, "Preparation time(hrs):", class: 'form-label' %>
          <%= form.text_field :preparation_time, :required => true, class: 'form-control', type: 'number', step: '0.1' %>
        </div>

        <div class="mb-3 w-50">
          <%= form.label :cooking_time, "Cooking time(hrs):", class: 'form-label' %>
          <%= form.text_field :cooking_time, :required => true, class: 'form-control', type: 'number', step: '0.1' %>
        </div>

        <div class="mb-3 w-50">
          <%= form.label :description, "Description:", class: 'form-label' %>
          <%= form.text_area :description, :required => true, class: 'form-control' %>
          <%= form.hidden_field :public, value: false %>
        </div>
        
        <div class="d-flex column-gap-3 justify-content-center">
          <%= form.submit "Create", class: 'btn btn-success fs-5' %>
          <%= link_to 'Cancel', recipes_path, class: 'btn btn-danger fs-5' %>
        </div>
      </div>
    <% end %>
  </end>
</section>

app/views/recipes/show.html.erb
<%= render partial: 'devise/shared/navbar' %>

<section class="text-center p-3">
  <h3 class="p-3"><%= @recipe.name %></h3>
  <div class="container text-start ps-4">
    <div class="row ps-4">
      <div class="col d-flex flex-column row-gap-3">
        <span>Preparation time: <%= @recipe.preparation_time %> hours</span>
        <span>Cooking time: <%= @recipe.cooking_time %></span>
      </div>
      <div class="col d-flex justify-content-end pe-5">
        <span class="d-flex column-gap-2">Public <%= public?(@recipe) %></public>
      </div>
    </div>
    <div class="row p-4">
      <div class="col">
        <%= @recipe.description %>
      </div>
    </div>
  </div>
  <div class="d-flex justify-content-around p-3">
    <%= details_buttons(@recipe) %>
  </div>
  <div class="container border-top p-3">
    <table class="table table-striped table-bordered">
      <tbody>
        <tr>
          <th>Food</th>
          <th>Quantity</th>
          <th>Value</th>
          <th>Actions</th>
        </tr>
        <%= render partial: 'table_rows', collection: foods(@recipe), as: :foods %>
      </tbody>
    </table>
  </div>
</section>