config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'foods#index'

  devise_for :users, controllers: { registrations: 'users/registrations' }

  resources :foods
  get 'recipe_foods/new/:id', to: 'recipe_foods#new', as: 'new_recipe_food'
  resources :recipe_foods
  resources :recipes
  resources :general_shopping_lists, only: [:index]
  resources :public_recipes, only: [:index]
  # Define any additional custom routes if needed
  
end

app/models/food.rb
class Food < ApplicationRecord
  belongs_to :user
  has_many :recipe_foods, dependent: :destroy
  has_many :recipes, through: :recipe_foods

  validates :name, presence: true
  validates :price, presence: true, numericality: { greater_than: 0 }
  validates :quantity, presence: true, numericality: { greater_than: 0 }
  validates :measurement_unit, presence: true
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  before_action :authenticate_user!
  def index
    @user = current_user
    order_direction = params[:sort] == 'name' && session[:sort_direction] == 'asc' ? 'desc' : 'asc'
    session[:sort_direction] = order_direction
    @foods = @user.foods.order("LOWER(name) #{order_direction}")
  end

  def new
    @food = Food.new
  end

  def destroy
    @food = current_user.foods.find(params[:id])
    if @food.destroy
      redirect_to foods_path, notice: 'Food was successfully destroyed.'
    else
      redirect_to foods_path, alert: 'Failed to destroy food.'
    end
  end

  def create
    @food = current_user.foods.build(food_params)

    if @food.save
      if exists?(@food.name)
        @food.destroy
        redirect_to foods_path, notice: "Food wasn't created because it already exist"
      else
        redirect_to foods_path, notice: 'Food was successfully created.'
      end
    else
      render :new
    end
  end

  private

  def food_params
    params.require(:food).permit(:name, :quantity, :measurement_unit, :price)
  end

  def exists?(food_name)
    foods = current_user.foods
    foods_names = foods.map { |food| food.name.downcase }
    pp cuantity_of_foods = foods_names.filter { |name| name == food_name.downcase }

    cuantity_of_foods.length > 1
  end
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/views/foods/index.html.erb
<%= render 'devise/shared/navbar' %>

<div class="container d-flex flex-column align-items-center mt-5">
  <h2 class="text-center"><%= @user.name %>'s Food</h2>
  <h2 class="text-center">Food List</h2>
  
  <% if notice %>
    <p class="notice alert alert-danger w-50"><%= notice %></p>
  <% end %>
  
  <% if alert %>
    <p class="alert"><%= alert %></p>
  <% end %>
  
  <div class="container d-flex justify-content-end mb-3 pe-0">
    <%= link_to "Add New Food", new_food_path, class: "btn btn-primary" %>
  </div>
  
  <table class="border table">
    <thead>
      <tr>
        <th class="food-name">
          Name
          <%= link_to '', foods_path(sort: 'name'), class: 'triangle-up' %>
        </th>
        <th>Measurement Unit</th>
        <th>Unit Price</th>
        <th>Quantity</th>
        <th>Actions</th>
      </tr>
    </thead>
    
    <tbody>
      <% @foods.each_with_index do |food, index| %>
        <tr class="<%= index.even? ? 'table-warning' : '' %>">
          <td><%= food.name %></td>
          <td><%= food.measurement_unit %></td>
          <td>$ <%= food.price %></td>
          <td><%= food.quantity %></td>
          <td>
            <%= button_to "Delete", food, method: :delete, class: "btn btn-danger btn-sm" %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/foods/new.html.erb
<%= render 'devise/shared/navbar' %>

<div class="container mt-5">
  <h1 class="text-center">Add New Food</h1>
    <% if @food.errors.any? %>
      <div class="alert alert-danger" role="alert" id="error_explanation">
        <ul class="m-0">
          <% @food.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
   <%= form_for @food, html: { class: "mt-3" } do |f| %>
    <div class="mb-3">
      <%= f.label :name, class: "form-label" %>
      <%= f.text_field :name, class: "form-control" %>
    </div>

    <div class="mb-3">
      <%= f.label :quantity, class: "form-label" %>
      <%= f.text_field :quantity, class: "form-control", type: 'number', step: '0.1' %>
    </div>

    <div class="mb-3">
      <%= f.label :measurement_unit, class: "form-label" %>
      <%= f.text_field :measurement_unit, class: "form-control" %>
    </div>

    <div class="mb-3">
      <%= f.label :price, class: "form-label" %>
      <%= f.text_field :price, class: "form-control", type: 'number', step: '0.1' %>
    </div>

    <%= f.submit "Save", class: "btn btn-primary w-100" %>
  <% end %>

  <%= link_to "Back to List", foods_path, class: "btn btn-secondary mt-3 w-100" %>
</div>